### ISSUE TITLE
Normalize ENS domain names before sending the transaction

### ISSUE THREAD

**Issue by rdig** [JoinColony/colonyJS#378]
This was originally caught by a bug in the dApp: JoinColony/colonyDapp#988

It's to do with the fact that ens name need to be normalized using `nameHash.normalize()` before being hashed and sent, to ensure the proper character encoding.

In this particular case it happened when using camelCase domain names. Eg: `cypressTestUser.user.joincolony.eth`

Note that this should also catch domain names with illegal characters. Eg: underscores _(`_`)_

**Comment by sprusr** [comment]
Some clarification on this for whoever takes it on: this is something which needs handling only when registering a new ENS name. All other ENS-related functions are expecting a namehash already (or address), so that should be handled before passing to colonyJS. When registering a name however, it is a string which is passed to the contract, so normalisation needs to happen within colonyJS. This can be done with `normalize` in [eth-ens-namehash](https://github.com/danfinlay/eth-ens-namehash).

**Comment by chmanie** [comment]
I think we might want to keep this in the dapp.
