### ISSUE TITLE
Standardize or remove the network names/ids used with getNetworkClient

### ISSUE THREAD

**Issue by bmiller59** [JoinColony/colonyJS#396]
The values to pass for the for the `network` string used with `getNetworkClient` are not clear and should be standardized and explained or removed.

For most dapps, the same code will be used in development and later when deployed for production use for a variety of networks (e.g. local, rinkeby, mainnet). As a result it would be beneficial to be able to look up the `network` string to pass in from ethers or web3 automatically.

Or perhaps a provider should be passed in instead of a network name?

It is not clear what values are expected and from the code the only value that seems to be used is `local`. Perhaps it not the network name that is needed but whether the dapp is running locally or remotely?

Thank you for clarifying.

**Comment by ryanchristo** [comment]
Thanks for sharing some ideas for improvements! The `getNetworkClient` method could definitely be improved upon. The primary reason it was added was to make it easier for developers to start building with colonyJS without having to understand loaders and adapters.

The `getNetworkClient` method currently only supports two network options: `local` and `rinkeby`. It does not support any other options because the colonyNetwork contracts have only been deployed to `rinkeby` and can be deployed locally for `local` development.

This method was not intended to replace the more custom configuration that is possible with loaders and adapters but it was brought to the forefront as a simple alternative. I do like the idea of passing a `provider` and being able to look up the `network` automatically. If we do this, the `provider` should be optional to maintain the simplicity of the method. Also, reading the `network` seems like a viable options that would definitely help with the primary objective of making it as simple as possible.

**Comment by chmanie** [comment]
There is support for that now. See here: https://github.com/JoinColony/colonyJS/blob/develop/src/constants.ts#L11
