### ISSUE TITLE
Can't log in as Metamask is falsely perceived as LOCKED.

### ISSUE THREAD

**Issue by entin-hun** [JoinColony/colonyJS#596]
## After I closed Metamask (the only offered wallet) popup window, and unlocked from extension, I still get this message:
`Metamask is locked. Please unlock it from the UI before proceeding`
How can I log in to Colony?

https://github.com/JoinColony/colonyJS/assets/50300541/a61333ec-7971-4c87-945a-727879b8c18e

**Comment by rdig** [comment]
Hi @entin-hun 

This issue is not related to the `colony-js` package, it's more related to the metamask extension you are using.

I will be closing it as it's not relevant here.

As for a specific fix for you, while we're not directly supporting Brave as a standalone browser (but rather just plain Chrome), a issue I'm spotting from your recording is that your account might not be connected to the Dapp

_(you can see your connected sites within the dropdown menu accessible from the top right of the extension interface)_

![Screenshot from 2024-03-07 23-23-29](https://github.com/JoinColony/colonyJS/assets/1193222/2c96f790-f9f9-482c-a4e6-e09f6fed48f9)

**Comment by entin-hun** [comment]
[Yes, Colony is included in the Connected sites.. Disconnecting there and connecting again haven't solved the issue.](https://youtu.be/OoOz-QA24FI)

**Comment by entin-hun** [comment]
I confirm that switching to Chrome solved it!
